name: test_task
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed: ^0.12.7
  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
  flutter_bloc: ^6.1.3
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.13

flutter:
  uses-material-design: true
